version: '3'
services:
  server:
    build: .
    network_mode: host
    command: yarn deploy
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    environment:
      NODE_ENV: development
volumes:
  reserved: